### ISSUE TITLE
Plugin outdated

### ISSUE THREAD

**Issue by sollevix67** [viktor-ferenczi/multigrid-projector#43]
16:07:14.7935 [ERROR]  Multigrid Projector: : Disabled the plugin due to potentially incompatible code changes in the game or plugin patch collisions. Please report the exception below on the SE Mods Discord (invite is on the Workshop page):; System.NotSupportedException: Refusing to load the plugin due to potentially incompatible code changes in the game:
Body of patched method MyGridPhysicalHierarchy.BreakLink has changed: actual dc95de5b, expected one of 72e7d0ea"
Body of patched method MyMechanicalConnectionBlockBase.CreateTopPart has changed: actual 192978a5, expected one of b37a7086"

Please reach out to the plugin author for an update.
   at MultigridProjector.Utilities.EnsureOriginal.VerifyAssembly(Assembly assembly)
   at MultigridProjectorServer.MultigridProjectorPlugin.Init(ITorchBase torch)

**Comment by viktor-ferenczi** [comment]
This happens if the game version is not supported by the Multigrid Projector plugin version loaded.

Does it happen with the client plugin (loaded by Plugin Loader) or on Dedicated Server / Torch Server?

Could you please attach a full log or send it to me on the SE Mods Discord? - You can do it in private chat as well.

The log is needed to verify the versions, since they are logged there.
