### ISSUE TITLE
Server crash, null pointer

### ISSUE THREAD

**Issue by InfernoSuperNova** [viktor-ferenczi/multigrid-projector#45]
One of our players keeps crashing the server when welding up his ship.
https://hatebin.com/adahmvljib
Here's the logs, please don't hesitate to ask any further questions.

**Comment by viktor-ferenczi** [comment]
There is no mention of `MultigridProjector` in the exception:
```
15:31:58.1552 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseBuildInternal_0(Object owner, Vector3I builder, Int64 requestInstant, Int64 builtBy, Boolean , Int64 )
   at Sandbox.Game.Entities.Blocks.MyProjectorBase.BuildInternal<>VRageMath_Vector3I#System_Int64#System_Int64#System_Boolean#System_Int64.Invoke(MyProjectorBase& this, Vector3I& cubeBlockPosition, Int64& owner, Int64& builder, Boolean& requestInstant, Int64& builtBy, DBNull& arg6)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6,T7](T1 arg1, T7 arg7, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, EndpointId endpointId, Nullable`1 position)
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseBuild_0(Object owner, MySlimBlock builder, Int64 requestInstant, Int64 builtBy, Boolean , Int64 )
   at SpaceEngineers.Game.Entities.Blocks.MyShipWelder.<>c__DisplayClass27_0.<Activate>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 316
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseBuildInternal_0(Object owner, Vector3I builder, Int64 requestInstant, Int64 builtBy, Boolean , Int64 )
   at Sandbox.Game.Entities.Blocks.MyProjectorBase.BuildInternal<>VRageMath_Vector3I#System_Int64#System_Int64#System_Boolean#System_Int64.Invoke(MyProjectorBase& this, Vector3I& cubeBlockPosition, Int64& owner, Int64& builder, Boolean& requestInstant, Int64& builtBy, DBNull& arg6)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6,T7](T1 arg1, T7 arg7, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, EndpointId endpointId, Nullable`1 position)
   at Patched_Sandbox.Game.Entities.Blocks.MyProjectorBaseBuild_0(Object owner, MySlimBlock builder, Int64 requestInstant, Int64 builtBy, Boolean , Int64 )
   at SpaceEngineers.Game.Entities.Blocks.MyShipWelder.<>c__DisplayClass27_0.<Activate>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 316
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by viktor-ferenczi** [comment]
Is the Multigrid Projector plugin loaded on server side?

**Comment by InfernoSuperNova** [comment]
It was, although it has since been disabled by the owner, temporarily

**Comment by viktor-ferenczi** [comment]
I cannot act on this report due to lack of information. The server side exception above does not contain any reference to the Multigrid Projector server plugin. There is no full log attached and no way for me to reproduce this situation.
