### ISSUE TITLE
with new version server dont start correct

### ISSUE THREAD

**Issue by dtmaster79** [viktor-ferenczi/multigrid-projector#47]
When I want to start my server (not Torch), it only starts until the plugin is loaded. Then you can't go any further. Here is an excerpt of the log.

```
2023-03-23 00:12:41.184 - Thread:  19 ->  Plugin Init: MultigridProjectorDedicated.MultigridProjectorPlugin
2023-03-23 00:12:41.185 - Thread:  19 ->  Info: Multigrid Projector: Loading
2023-03-23 00:12:41.644 - Thread:  19 ->  Error: Multigrid Projector: Failed to load; System.ArgumentException: Path cannot be the empty string or all whitespace.
   at System.IO.Directory.CreateDirectory(String path)
   at HarmonyLib.FileLog.get_LogPath()
   at HarmonyLib.FileLog.Log(String str)
   at HarmonyLib.Harmony..ctor(String id)
   at MultigridProjectorDedicated.MultigridProjectorPlugin.get_Harmony()
   at MultigridProjectorDedicated.MultigridProjectorPlugin.Init(Object gameInstance)
2023-03-23 00:12:41.679 - Thread:  19 ->  Exception occurred: System.ArgumentException: Path cannot be the empty string or all whitespace.
   at System.IO.Directory.CreateDirectory(String path)
   at HarmonyLib.FileLog.get_LogPath()
   at HarmonyLib.FileLog.Log(String str)
   at HarmonyLib.Harmony..ctor(String id)
   at MultigridProjectorDedicated.MultigridProjectorPlugin.get_Harmony()
   at MultigridProjectorDedicated.MultigridProjectorPlugin.Init(Object gameInstance)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.WindowsService.MainThreadStart(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
2023-03-23 00:12:41.680 - Thread:  19 ->  Showing message
2023-03-23 00:12:43.533 - Thread:  19 ->  
================================== CRASH INFO ==================================
AppVersion: 01_201_014
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 47
PCUCount: 10014
IsHang: False
GCMemory: 439
GCMemoryAllocated: 439
HWAvailableMemory: 48888
ProcessPrivateMemory: 1569
AnalyticId: SEDS
================================== OFNI HSARC ==================================

2023-03-23 00:12:43.533 - Thread:  19 ->  Log Closed
```

**Comment by viktor-ferenczi** [comment]
You need to have `0Harmony.dll` as well in the same folder as `MultigridProjectorDedicated.dll`. Apparently the plugin fails to load it for some reason. Both are included in the current `MultigridProjectorDedicated-v0.4.15.zip` file.

**Comment by dtmaster79** [comment]
I have the file in the folder. I have both dll in one folder. I deleted the old ones and replaced them with the new ones. And then the server only started. So it can't be because of the missing dll.

**Comment by viktor-ferenczi** [comment]
Are you running this Dedicated Server locally on your machine or at a game server hosting provider?

**Comment by dtmaster79** [comment]
No, it doesn't run on my local PC. And no, I don't use game server hosters (Nitrado, Gportal, etc). I host it myself on my root server.

**Comment by viktor-ferenczi** [comment]
Changes made since 0.4.13:
- **0.4.14** https://github.com/viktor-ferenczi/multigrid-projector/pull/44
- **0.4.15** https://github.com/viktor-ferenczi/multigrid-projector/pull/46

Question is which one of these may cause your issue?

**Comment by dtmaster79** [comment]
So far only the 0.4.15. I can't tell you a version 0.4.14. There is no 0.4.14 to download.

**Comment by viktor-ferenczi** [comment]
It is safe to use 0.4.13 for now. Once the major game update drops I will release a new version. 0.4.14 was only for the SE beta. 0.4.13 has the same features as 0.4.15, only change is that 0.4.15 can disable the code verification causing issues on Proton (Linux).

**Comment by viktor-ferenczi** [comment]
Also, MGP 0.4.13 on the server can be used with the latest MGP client plugin from Plugin Loader, so there should be no issue with compatibility either.

**Comment by dtmaster79** [comment]
Thanks for the info.
