### ISSUE TITLE
0.7.0 seems to fail to compile

### ISSUE THREAD

**Issue by PROMETHIA-27** [viktor-ferenczi/multigrid-projector#78]
When launching the game as of about 40 minutes after 0.70 has been released, it fails to load with the following error:
```
2024-05-04 15:34:11.862 - Thread:   1 ->  [PluginLoader] [Info] Downloading https://github.com/viktor-ferenczi/multigrid-projector/archive/ff9143a627450e6162f4bf9dd4a74794ec3ec085.zip
2024-05-04 15:34:15.862 - Thread:   1 ->  [PluginLoader] [Error] CS0165: Use of unassigned local variable 'blockDefinition' in file:
multigrid-projector-ff9143a627450e6162f4bf9dd4a74794ec3ec085/MultigridProjector/Extensions/MyObjectBuilderExtensions.cs (86,166)
2024-05-04 15:34:15.868 - Thread:   1 ->  [PluginLoader] [Error] Failed to load viktor-ferenczi/multigrid-projector|Multigrid Projector because of an error: System.Exception: Compilation failed!
   at avaness.PluginLoader.Compiler.RoslynCompiler.Compile(String assemblyName, Byte[]& symbols)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(String commit, String assemblyName, Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)
```

**Comment by joaogubert** [comment]
Same issue here!

![image](https://github.com/viktor-ferenczi/multigrid-projector/assets/7991508/935ba1fe-6311-40e1-88b4-64f135b0bd9e)

**Comment by zajc3w** [comment]
same here 
`2024-05-04 21:25:15.048 - Thread:   1 ->  [PluginLoader] [Info] Downloading https://github.com/viktor-ferenczi/multigrid-projector/archive/ff9143a627450e6162f4bf9dd4a74794ec3ec085.zip
2024-05-04 21:25:17.650 - Thread:   1 ->  [PluginLoader] [Error] CS0165: Use of unassigned local variable 'blockDefinition' in file:
multigrid-projector-ff9143a627450e6162f4bf9dd4a74794ec3ec085/MultigridProjector/Extensions/MyObjectBuilderExtensions.cs (86,166)
2024-05-04 21:25:17.656 - Thread:   1 ->  [PluginLoader] [Error] Failed to load viktor-ferenczi/multigrid-projector|Multigrid Projector because of an error: System.Exception: Compilation failed!
   at avaness.PluginLoader.Compiler.RoslynCompiler.Compile(String assemblyName, Byte[]& symbols)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(String commit, String assemblyName, Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)
2024-05-04 21:25:19.314 - Thread:   1 ->  [PluginLoader] [Info] Finished startup. Took 5441ms`

**Comment by kalazzerx** [comment]
Same issue - had to disable/remove plugin 

2024-05-04 17:47:17.264 - Thread:   1 ->  [PluginLoader] [Info] Downloading https://github.com/viktor-ferenczi/multigrid-projector/archive/ff9143a627450e6162f4bf9dd4a74794ec3ec085.zip
2024-05-04 17:47:20.110 - Thread:   1 ->  [PluginLoader] [Error] CS0165: Use of unassigned local variable 'blockDefinition' in file:
multigrid-projector-ff9143a627450e6162f4bf9dd4a74794ec3ec085/MultigridProjector/Extensions/MyObjectBuilderExtensions.cs (86,166)
2024-05-04 17:47:20.120 - Thread:   1 ->  [PluginLoader] [Error] Failed to load viktor-ferenczi/multigrid-projector|Multigrid Projector because of an error: System.Exception: Compilation failed!
   at avaness.PluginLoader.Compiler.RoslynCompiler.Compile(String assemblyName, Byte[]& symbols)
   at avaness.PluginLoader.Data.GitHubPlugin.CompileFromSource(String commit, String assemblyName, Action`1 callback)
   at avaness.PluginLoader.Data.GitHubPlugin.GetAssembly()
   at avaness.PluginLoader.Data.PluginData.TryLoadAssembly(Assembly& a)

**Comment by kalazzerx** [comment]
I figured out how to get it to work - I downloaded the newest version of plugin loader and replace my old version and now the plugin is loading successfully.  I also unchecked the old version of the plugin and added it back - not sure if that was part of the solution.

**Comment by PROMETHIA-27** [comment]
Simply reinstalling multigrid projector itself (without reinstalling the loader, which seems to already be up to date) fixed it for me. I assume the merged PR fixed it.
