### ISSUE TITLE
`NullReferenceException` in `MyBlueprintIdTracker.OnAdded`

### ISSUE THREAD

**Issue by viktor-ferenczi** [viktor-ferenczi/multigrid-projector#91]
This exception is logged when the server (Torch or DS) loads the world (it is handled by MGP's own error handling).

```
16:44:58.5704 [ERROR]  Multigrid Projector: : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Game.Entities.MyBlueprintIdTracker.OnAdded(MyProjectorBase projector, HashSet`1 reservedIds)
   at Sandbox.Game.Entities.Blocks.MyProjectorBase.SetNewBlueprint(List`1 gridBuilders)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MultigridProjectorServer.Patches.MyProjectorBase_Remap.Prefix(MyProjectorBase __instance)
```

This seems to be harmless, but still not nice to happen.

**Root cause:** `MyBlueprintIdTracker.OnTrackedIdAdded` is `null` in the `MyBlueprintIdTracker.OnAdd` method.

**Crashing code line:**
```cs
MyBlueprintIdTracker.OnTrackedIdAdded.InvokeIfNotNull(reservedIds, projector);
```

**Workaround:** Add listeners to all three event handlers defined in `MyBlueprintIdTracker`, so they are never `null`.

**Comment by viktor-ferenczi** [comment]
Workaround implemented in MGP 0.7.6. This may be obsolete once #92 is solved.
