### ISSUE TITLE
ArgumentException: Only primitive types are allowed for action parameters

### ISSUE THREAD

**Issue by viktor-ferenczi** [viktor-ferenczi/multigrid-projector#96]
An exception happened while attempting to weld the door of the [Cube](https://steamcommunity.com/sharedfiles/filedetails/?id=3366231620) using the combination of a MnM Projector and an active B&R at the same time. It welded the first 3-4 blocks, but when it reached the MnM Projector on the door it failed with the exception below and the projection disappeared.

```
2024-11-15 18:25:34.202 - Thread:   1 ->  Error: Multigrid Projector: System.ArgumentException: Only primitive types are allowed for action parameters
Parameter name: value
   at Sandbox.ModAPI.Ingame.TerminalActionParameter.AssertTypeCodeValidity(TypeCode typeCode)
   at Sandbox.ModAPI.Ingame.TerminalActionParameter.Deserialize(String serializedValue, TypeCode typeCode)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemTerminalGroup.Init(MyObjectBuilder_ToolbarItem objBuilder)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemFactory.CreateToolbarItem(MyObjectBuilder_ToolbarItem data)
   at MultigridProjectorClient.Utilities.UpdateToolbar.CopyToolbars(MyTerminalBlock sourceBlock, MyTerminalBlock destinationBlock)
   at MultigridProjectorClient.Utilities.UpdateBlock.CopyProperties(MyTerminalBlock sourceBlock, MyTerminalBlock destinationBlock)
   at MultigridProjectorClient.Utilities.Construction.<>c__DisplayClass7_0.<WeldBlock>g__OnPreviewPlace|0(MyCubeBlock builtBlock)
   at MultigridProjector.Utilities.Events.<>c__DisplayClass0_0.<InvokeOnGameThread>g__safeTask|0()
```

**Comment by SpaceGT** [comment]
A game update has broken the creation of placeholder toolbar groups.
This logic is being replaced with a new class in https://github.com/viktor-ferenczi/multigrid-projector/pull/81
