### ISSUE TITLE
Target Invocation Exception

### ISSUE THREAD

**Issue by snowboundmage2** [viktor-ferenczi/multigrid-projector#98]
2024-12-29 16:29:36.426 - Thread:   1 ->  Error: Multigrid Projector: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sandbox.Game.Entities.MyBlueprintIdTracker.OnAdded(MyProjectorBase projector, HashSet`1 reservedIds)
   at Sandbox.Game.Entities.Blocks.MyProjectorBase.SetNewBlueprint(List`1 gridBuilders)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MultigridProjectorClient.Patches.MyProjectorBase_SetNewBlueprint.Prefix(MyProjectorBase __instance)

Got this message in game. Told me to report it to here.

**Comment by viktor-ferenczi** [comment]
Related to #92

Could not reproduce this so far.
